# https://taskfile.dev

version: "3"

env:
  DOCKER_BUILDKIT: 0
  COMPOSE_DOCKER_CLI_BUILD: 0
  DOCKER_DEFAULT_PLATFORM: "linux/amd64"
  DOCKER_SCAN_SUGGEST: false

includes:
  app:
    taskfile: ./lambda/go
    optional: true
    internal: true
    dir: ./lambda/go

tasks:
  install:
    desc: install tools
    cmds:
      - brew install colima

  init:
    desc: init project - install npm packages for lambda once
    cmds:
      - cd lambda/ts && npm install

  update:
    desc: update npm packages
    cmds:
      - npm outdated
      - npm update
      - npm install -g npm-check-updates
      - ncu -u
      - npm install
    ignore_error: true

  bootstrap:
    deps: [app:build]
    desc: CDK bootstrap (for beginners)
    vars:
      ALIAS:
        sh: aws iam list-account-aliases --query "AccountAliases[0]" --output=text

    cmds:
      - cdk  bootstrap

  colima:
    desc: 1) start colima docker
    cmds:
      - colima start

  deploy:
    deps: [app:build]
    desc: 2) Deploy cdk without asking - needs docker
    cmds:
      - cdk deploy --require-approval never
    silent: true

  diff:
    desc: cdk diff (with all env vars)
    cmds:
      - cdk diff --require-approval never
    silent: true

  traffic:
    desc: Create traffic on S3 bucket
    cmds:
      - test/traffic.sh
